# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.5"
manifest_format = "2.0"
project_hash = "a3f924e0550ed12b08b5928de91b16b2e838264b"

[[deps.LaplaceMFS]]
path = "."
uuid = "31bf14b4-1cb9-4d64-bb39-ecf61c765b8a"
version = "1.0.0-DEV"
